nacos:
  config:
    server-addr: http://94.74.120.122:8848
    #server-addr: 172.16.32.220:8848 #内网
    namespace:  test
    #namespace: a173ae57-6dc2-4f08-bda7-194b5d8ecdaf #pro
    data-id: admin.yaml
    group: JX_GROUP
    bootstrap:
      enable: true
      log-enable: true
    type: yaml



spring:

  application:
    name: admin
#  profiles:
#    active: dev

#logging:
#  level:
#    root: info

  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    #发布到运营时候修改该配置 online
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 1000MB
      # 设置总上传的文件大小
      max-request-size: 1000MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.ruoyi.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
