nacos:
  config:
    server-addr: mse-c14908614-p.nacos-ans.mse.aliyuncs.com:8848
    #server-addr: 172.16.32.220:8848 #内网
    namespace: 4ea7a38e-32fd-4ddd-b384-dc5ad4bd753d #test
    #namespace: a173ae57-6dc2-4f08-bda7-194b5d8ecdaf #pro
    data-id: admin.yaml
    group: JX_GROUP
    bootstrap:
      enable: true
      log-enable: true
    type: yaml



spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: admin
#  profiles:
#    active: dev

#logging:
#  level:
#    root: info

  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages