nacos:
  config:
    #server-addr: 47.242.206.196:8848
    server-addr: 172.16.32.220:8848 #内网
    #namespace: 4ea7a38e-32fd-4ddd-b384-dc5ad4bd753d #test
    namespace: a173ae57-6dc2-4f08-bda7-194b5d8ecdaf #pro
    data-id: admin.yaml
    group: JX_GROUP
    bootstrap:
      enable: true
      log-enable: true
    type: yaml



spring:
  application:
    name: admin
#  profiles:
#    active: dev

#logging:
#  level:
#    root: info

  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages